### ISSUE TITLE
Only Japanese Documents?

### ISSUE THREAD

**Issue by gmlwns2000** [harujoh/KelpNet#20]
I am so happy to see this awesome deep learning library in C#.

But I have trouble to read Japanese documentation in code. Are there some documents that written in English? Or just should I use google translator?

Thanks for making this nice library @harujoh again.

**Comment by harujoh** [comment]
I am very honoured by your compliment.
But sorry, Currently only written in Japanese.

I can read comments thanks to machine translators.
However, English documents can not be maintained.
Because, I do not have English-speaking skills.

Therefore, you only have to rely on machine translation at the moment.

I am very sorry about this situation.


お褒めの言葉をいただき、大変光栄に思います。
しかし申し訳ありません、現在のところドキュメントは日本語のみです。

私は機械翻訳のお陰でコメントを読むことができます。
しかし、英語のドキュメントを整備することができません。
なぜなら、私が英語を話すスキルを持っていないからです。

したがって、現在のところ機械翻訳に頼っていただくしかありません。

私はこの現状を大変申し訳なく感じています。

**Comment by gmlwns2000** [comment]
Hi @harujoh ,

Thanks for thinking about it.
I have bad skills at en and jp both :3 I will keep use google translator then.
However, I created [a little tool](https://github.com/Kawaian/CodeTranslater) for auto translate c# jp comments to eng comments.
And this is English translated [KelpNet](https://github.com/Kawaian/KelpNet). @
