### ISSUE TITLE
.Net Standard Supports?

### ISSUE THREAD

**Issue by gmlwns2000** [harujoh/KelpNet#21]
Any plans for it yet?

This library seems nice to support it. Most of the codes are just depends on DotNet standard libraries. If we support DotNet standard, KelpNet will be runnable in mobile or Linux too.

**Comment by harujoh** [comment]
I have considered that support.
However, we did not implement it because we needed more effort than we expected, so we did not match cost-effectiveness.

I used this tool for investigation
[.NET Compatibility Diagnostics]
https://blogs.msdn.microsoft.com/dotnet/2016/03/03/net-framework-compatibility-diagnostics/


私はその検討を行ったことがあります。
しかし、期待した以上に多くの作業が必要で、費用対効果に見合わなかったため実装しませんでした。

私は検討にこのツールを使いました。

[.NET Compatibility Diagnostics]
https://blogs.msdn.microsoft.com/dotnet/2016/03/03/net-framework-compatibility-diagnostics/

**Comment by gmlwns2000** [comment]
Hmm then I will have to transplant it myself when I need it later....

Thanks, @harujoh
